proc string NamePicker()
{
    string $names[] = {"Dave", "Doug", "Clarence", "Mary", "Jane", "Tina", "Phil"};
    int $size = size($names);
    int $randNum = `rand $size`;
    return ($names[$randNum]);
}

proc int RandomNumber(int $num)
{
    int $randNum = `rand $num`;
    print ("This random number is " + $randNum + "\n");
    return ($randNum);
}

print (RandomNumber(100) + RandomNumber(100) + "\n");

print (NamePicker() + "'s favorite number is " + RandomNumber(100) + "!\n");
